### ISSUE TITLE
[META] Add analytics to the site

### ISSUE THREAD

**Issue by 1Copenut** [1Copenut/c3-eleventy#109]
## UPDATE 7/16
I decided to go with [Umami GDPR-compliant analytics](https://umami.is/) for a variety of reasons. It's open-source, has a free tier, and was super-easy to set up. Most importantly, it doesn't stomp on anyone's privacy. And that matters.

## Description
Analytics are key to ensuring I know what's going on, and how users are interacting with the sit (or not :( ). Here's a few ideas to get started:

- [ ] [Plausible analytics package](https://plausible.io/) $10/mo
- [ ] [Adding Complementary Performance Data to Your Site](https://www.htmhell.dev/adventcalendar/2022/12/)
- [ ] [How to track Web Monetization events using Plausible](https://www.jeremiahlee.com/posts/web-monetization-events-in-plausible/)
- [ ] [Eleventy monetization plugin](https://github.com/DanCanetti/eleventy-plugin-monetization)
